#!/usr/bin/python3
# -*- coding: utf-8 -*-
# How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
powers = set()

for a in range(2,101):
    for b in range(2,101):
        powers.add(a**b)

print(len(powers))
