#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.

def T(n):
    return(n*(n+1)/2)

def P(n):
    return(n*(3*n-1)/2)

def H(n):
    return(n*(2*n-1))
triangle=[]
pentagonal=[]
hexagonal=[]
for i in range(144,60000):
    triangle.append(T(i))
    pentagonal.append(P(i))
    hexagonal.append(H(i))
for i in hexagonal:
    if (pentagonal.count(i)==1 and triangle.count(i)==1):
        print(i)
        break
