#!/usr/bin/python3
# -*- coding: utf-8 -*-
# How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?
powers = []

for a in range(2,101):
    for b in range(2,101):
        powers.append(a**b)

powers.sort()

for n in powers:
    while powers.count(n)>1:
        powers.remove(n)

print(len(powers))
