#!/usr/bin/python3
# -*- coding: utf-8 -*-
# Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk − Pj| is minimised; what is the value of D?

def P(n):
    return(int(n*(3*n-1)/2))

pentagons = []
for n in range(1,10000):
    pentagons.append(P(n))

for p in pentagons:
    for q in pentagons[(pentagons.index(p)+1):]:
        if(pentagons.count(p+q)==1):
            if(pentagons.count(q-p)==1):
                print(q-p)
